### ISSUE TITLE
 Getting error when executing terraform-azure.sh

### ISSUE THREAD

**Issue by mesgar** [ruzickap/k8s-postgresql#81]
Hi,

I got the following error when I ran [./terraform-${CLOUD_PLATFORM}.sh init].

WARNING: There are no credentials provided in your command and environment, we will query for the account key inside your storage account. 
Please provide --connection-string, --account-key or --sas-token as credentials, or use `--auth-mode login` if you have required RBAC roles in your command. For more information about RBAC roles in storage, visit https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-cli. 
Setting the corresponding environment variables can avoid inputting credentials in your command. Please use --help to get more information.
{
  "created": true
}
./terraform-azure.sh: line 71: /usr/local/bin/terraform: cannot execute binary file

Regards

**Comment by ruzickap** [comment]
Hello.

The code is quite old and and I'm not sure if it is still working.
I wouldn't rely on it as a whole, but you can still use some parts which may work.

See you

**Comment by mesgar** [comment]
Hi,

Thanks for quick response.
I needed a mac version of terraform and there was some issue with container name.
Now it gives me different warning and errors.
I'll find a way to install PostgreSQL HA on Azure AKS.

Thanks


Initializing modules...
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Warning: Interpolation-only expressions are deprecated

  on azure.tf line 16, in resource "azurerm_kubernetes_cluster" "kubernetes_cluster":
  16:       key_data = "${file("${var.ssh_public_key}")}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and 18 more similar warnings elsewhere)


Warning: Version constraints inside provider configuration blocks are deprecated

  on main.tf line 11, in provider "azurerm":
  11:   version = "1.33.1"

Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.

(and one more similar warning elsewhere)


Warning: Quoted keywords are deprecated

  on ../modules/k8s_initial_config/cert-manager.tf line 25, in resource "null_resource" "cert-manager-crds":
  25:     when    = "destroy"

In this context, keywords are expected literally rather than in quotes.
Terraform 0.11 and earlier required quotes, but quoted keywords are now
deprecated and will be removed in a future version of Terraform. Remove the
quotes surrounding this keyword to silence this warning.

(and 2 more similar warnings elsewhere)


Error: Invalid reference from destroy provisioner

  on ../modules/k8s_initial_config/cert-manager.tf line 26, in resource "null_resource" "cert-manager-crds":
  26:     command = "kubectl delete --kubeconfig=${var.kubeconfig} -f ${data.http.crd_cert-manager.url}"

Destroy-time provisioners and their connection configurations may only
reference attributes of the related resource, via 'self', 'count.index', or
'each.key'.

References to other resources during the destroy phase can cause dependency
cycles and interact poorly with create_before_destroy.


Error: Invalid reference from destroy provisioner

  on ../modules/k8s_initial_config/cert-manager.tf line 26, in resource "null_resource" "cert-manager-crds":
  26:     command = "kubectl delete --kubeconfig=${var.kubeconfig} -f ${data.http.crd_cert-manager.url}"

Destroy-time provisioners and their connection configurations may only
reference attributes of the related resource, via 'self', 'count.index', or
'each.key'.

References to other resources during the destroy phase can cause dependency
cycles and interact poorly with create_before_destroy.


Error: Invalid reference from destroy provisioner

  on ../modules/k8s_initial_config/cert-manager.tf line 97, in resource "null_resource" "cert-manager-clusterissuer":
  97:     command = "kubectl delete --kubeconfig=${var.kubeconfig} -f -<<EOF\n${data.template_file.cert-manager-clusterissuer.rendered}\nEOF"

Destroy-time provisioners and their connection configurations may only
reference attributes of the related resource, via 'self', 'count.index', or
'each.key'.

References to other resources during the destroy phase can cause dependency
cycles and interact poorly with create_before_destroy.


Error: Invalid reference from destroy provisioner

  on ../modules/k8s_initial_config/cert-manager.tf line 97, in resource "null_resource" "cert-manager-clusterissuer":
  97:     command = "kubectl delete --kubeconfig=${var.kubeconfig} -f -<<EOF\n${data.template_file.cert-manager-clusterissuer.rendered}\nEOF"

Destroy-time provisioners and their connection configurations may only
reference attributes of the related resource, via 'self', 'count.index', or
'each.key'.

References to other resources during the destroy phase can cause dependency
cycles and interact poorly with create_before_destroy.


Error: Invalid reference from destroy provisioner

  on ../modules/k8s_initial_config/cert-manager.tf line 123, in resource "null_resource" "cert-manager-certificate":
 123:     command = "kubectl delete --kubeconfig=${var.kubeconfig} -f -<<EOF\n${data.template_file.cert-manager-certificate.rendered}\nEOF"

Destroy-time provisioners and their connection configurations may only
reference attributes of the related resource, via 'self', 'count.index', or
'each.key'.

References to other resources during the destroy phase can cause dependency
cycles and interact poorly with create_before_destroy.


Error: Invalid reference from destroy provisioner

  on ../modules/k8s_initial_config/cert-manager.tf line 123, in resource "null_resource" "cert-manager-certificate":
 123:     command = "kubectl delete --kubeconfig=${var.kubeconfig} -f -<<EOF\n${data.template_file.cert-manager-certificate.rendered}\nEOF"

Destroy-time provisioners and their connection configurations may only
reference attributes of the related resource, via 'self', 'count.index', or
'each.key'.

References to other resources during the destroy phase can cause dependency
cycles and interact poorly with create_before_destroy.
